repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.104.0
    hooks:
      - id: terraform_fmt
        name: terraform fmt
      - id: terraform_tflint
        name: tflint

  # note that pre-commit-terraform does have a built-in terraform_docs hook, but it does not
  # handle things like recursive.enabled: true well. recommended using this official terraform-docs
  # hook instead
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.21.0
    hooks:
      - id: terraform-docs-go
        args: ["--recursive=false", "."]
        files: ^(main\.tf|inputs\.tf|README\.md|.*\.tf)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      - id: ruff-check
      - id: ruff-format
